# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-22 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_auto_20180222_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='Status',
            field=models.CharField(blank=True, default='1', max_length=100),
        ),
    ]
